/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-04-12 08:04:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/resources/css/styles/Login.css", Long.valueOf(1523438586225L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t");
      out.write(".form-signin\r\n");
      out.write("{\r\n");
      out.write("    max-width: 330px;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write(".form-signin .form-signin-heading, .form-signin .checkbox\r\n");
      out.write("{\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".form-signin .checkbox\r\n");
      out.write("{\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write(".form-signin .form-control\r\n");
      out.write("{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    -webkit-box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".form-signin .form-control:focus\r\n");
      out.write("{\r\n");
      out.write("    z-index: 2;\r\n");
      out.write("}\r\n");
      out.write(".form-signin input[type=\"text\"]\r\n");
      out.write("{\r\n");
      out.write("    margin-bottom: -1px;\r\n");
      out.write("    border-bottom-left-radius: 0;\r\n");
      out.write("    border-bottom-right-radius: 0;\r\n");
      out.write("}\r\n");
      out.write(".form-signin input[type=\"password\"]\r\n");
      out.write("{\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    border-top-left-radius: 0;\r\n");
      out.write("    border-top-right-radius: 0;\r\n");
      out.write("}\r\n");
      out.write(".account-wall\r\n");
      out.write("{\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    padding: 40px 0px 20px 0px;\r\n");
      out.write("    background-color: pink;\r\n");
      out.write("    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write(".login-title\r\n");
      out.write("{\r\n");
      out.write("    color: #555;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write(".profile-img\r\n");
      out.write("{\r\n");
      out.write("    width: 96px;\r\n");
      out.write("    height: 96px;\r\n");
      out.write("    margin: 0 auto 10px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    -moz-border-radius: 50%;\r\n");
      out.write("    -webkit-border-radius: 50%;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write(".need-help\r\n");
      out.write("{\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write(".new-account\r\n");
      out.write("{\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/header.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-6 col-md-4 col-md-offset-4\">\r\n");
      out.write("            <h1 class=\"text-center login-title\">Sign in to Purchase</h1>\r\n");
      out.write("            <div class=\"account-wall\">\r\n");
      out.write("                <img class=\"profile-img\" src=\"https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120\"\r\n");
      out.write("                    alt=\"\">\r\n");
      out.write("                <form class=\"form-signin\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"Email\" required autofocus>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" placeholder=\"Password\" required>\r\n");
      out.write("                <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\">\r\n");
      out.write("                    Sign in</button>\r\n");
      out.write("                <label class=\"checkbox pull-left\">\r\n");
      out.write("                    <input type=\"checkbox\" value=\"remember-me\">\r\n");
      out.write("                    Remember me\r\n");
      out.write("                </label>\r\n");
      out.write("                <a href=\"#\" class=\"pull-right need-help\">Need help? </a><span class=\"clearfix\"></span>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"#\" class=\"text-center new-account\">Create an account </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
