/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-04-13 07:56:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/resources/css/styles/signUp.css", Long.valueOf(1523606129542L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t");
      out.write("/* body{\r\n");
      out.write("background:url();\r\n");
      out.write("background-size:cover;\r\n");
      out.write("} */\r\n");
      out.write(".sign_up{\r\n");
      out.write("border-radius:5px;\r\n");
      out.write("background:pink;\r\n");
      out.write("padding:20px;\r\n");
      out.write("width:420px;\r\n");
      out.write("margin:auto;\r\n");
      out.write("color:#fff;\r\n");
      out.write("font-size:16px;\r\n");
      out.write("font-family:Verdana;\r\n");
      out.write("margin-top:100px;\r\n");
      out.write("}\r\n");
      out.write(".sign_up h1{\r\n");
      out.write("text-align:center;\r\n");
      out.write("margin:0;\r\n");
      out.write("padding:0;\r\n");
      out.write("}\r\n");
      out.write(".sign_up input,select{\r\n");
      out.write("padding:12px 20px;\r\n");
      out.write("margin:8px \"src/main/webapp/WEB-INF/resources/css/styles/signUp.css\"0;\r\n");
      out.write("display:inline-block;\r\n");
      out.write("border:1px solid #ccc;\r\n");
      out.write("border-radius:4px;\r\n");
      out.write("box-sizing:border-box;\r\n");
      out.write("font-size:18px;\r\n");
      out.write("background:Black;\r\n");
      out.write("color:white;\r\n");
      out.write("opacity:0.9;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".sign_up input[type=submit]{\r\n");
      out.write("width:100%;\r\n");
      out.write("border:none;\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("#fname{\r\n");
      out.write("width:49%;\r\n");
      out.write("}\r\n");
      out.write("#lname{\r\n");
      out.write("width:49.5%;\r\n");
      out.write("}\r\n");
      out.write("#email{\r\n");
      out.write("width:100%;\r\n");
      out.write("}\r\n");
      out.write("#password{\r\n");
      out.write("width:49.5%;\r\n");
      out.write("}\r\n");
      out.write("#re_password{\r\n");
      out.write("width:49%;\r\n");
      out.write("}\r\n");
      out.write("input[type=submit]:hover{\r\n");
      out.write("background:#45049;\r\n");
      out.write("transition:0.6s\r\n");
      out.write("}\r\n");
      out.write("option{\r\n");
      out.write("color:white;\r\n");
      out.write("background:purple;\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/header.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"sign_up\">\r\n");
      out.write("<form>\r\n");
      out.write("<h1>Sign Up Here</h1>\r\n");
      out.write("<hr>\r\n");
      out.write("<input type=\"text\" name=\"fname\" id=\"fname\" placeholder=\"your Firstname\" required>\r\n");
      out.write("<input type=\"text\" name=\"lname\" id=\"lname\" placeholder=\"your Lastname \" required>\r\n");
      out.write("<input type=\"text\" name=\"email\" id=\"email\" placeholder=\"your email or phone number \"required>\r\n");
      out.write("<input type=\"text\" name=\"password\" id=\"password\" placeholder=\"yourpassword\" \"required>\r\n");
      out.write("<input type=\"text\" name=\"re_password\" id=\"re_password\" placeholder=\"your re_password \"required>\r\n");
      out.write("<div class=\"date_of_birth\">\r\n");
      out.write("<span style=\"font-size:18px\";> Date of birth</span><br>\r\n");
      out.write("<select name=\"DOBMonth\">\r\n");
      out.write("<option> Month</option>\r\n");
      out.write("<option value=\"January\">January</option>\r\n");
      out.write("<option value=\"February\">February</option>\r\n");
      out.write("</select>\r\n");
      out.write("<select name=\"DOBDay\">\r\n");
      out.write("<option> Day</option>\r\n");
      out.write("<option value=\"1\">1</option>\r\n");
      out.write("<option value=\"2\">2</option>\r\n");
      out.write("</select>\r\n");
      out.write("<select name = \"DOBYear\">\r\n");
      out.write("<option>Year</option>\r\n");
      out.write("<option value=\"1990\">1990</option>\r\n");
      out.write("<option value=\"2000\">2000</option>\r\n");
      out.write("</select>\r\n");
      out.write("<br>\r\n");
      out.write("<input type=\"radio\" name=\"male\" value=\"male\">Male\r\n");
      out.write("<input type=\"radio\" name=\"female\" value=\"female\">Female\r\n");
      out.write("<input type=\"submit\" value=\"create a Account\">\r\n");
      out.write("<input type=\"checkbox\"> I Accept Terms and Conditions\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
